namespace RedisDiagnostic.SourceGenerator;

internal static class InstrumentedDatabaseSourceWriter
{
    internal static string Write(INamedTypeSymbol databaseType)
    {
        StringBuilder builder = new(64 * 1024);
        AppendClassHeader(builder);

        Dictionary<string, IMethodSymbol> emitted = new(StringComparer.Ordinal);
        HashSet<string> emittedProperties = new(StringComparer.Ordinal);
        foreach (var member in DatabaseInterfaceMembers.Enumerate(databaseType))
        {
            if (member is IPropertySymbol property)
            {
                if (!emittedProperties.Add(property.Name))
                {
                    continue;
                }

                InstrumentedPropertyWriter.Write(builder, property);
                continue;
            }

            if (member is not IMethodSymbol { MethodKind: MethodKind.Ordinary } method)
            {
                continue;
            }

            AppendUniqueMethod(builder, method, emitted);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendClassHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591");
        builder.AppendLine("#pragma warning disable SER007, SER008");
        builder.AppendLine();
        builder.AppendLine("namespace RedisDiagnostic;");
        builder.AppendLine();
        builder.AppendLine("public sealed class InstrumentedDatabase : global::StackExchange.Redis.IDatabase");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::StackExchange.Redis.IDatabase _inner;");
        builder.AppendLine("    private readonly global::RedisDiagnostic.IRedisMethodMetrics _metrics;");
        builder.AppendLine();
        builder.AppendLine("    public InstrumentedDatabase(global::StackExchange.Redis.IDatabase inner, global::RedisDiagnostic.IRedisMethodMetrics metrics)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(inner);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(metrics);");
        builder.AppendLine("        _inner = inner;");
        builder.AppendLine("        _metrics = metrics;");
        builder.AppendLine("    }");
    }

    private static void AppendUniqueMethod(
        StringBuilder builder,
        IMethodSymbol method,
        Dictionary<string, IMethodSymbol> emitted)
    {
        var key = DatabaseInterfaceMembers.GetSignatureKey(method);
        if (!emitted.TryGetValue(key, out var existing))
        {
            emitted[key] = method;
            InstrumentedMethodWriter.Write(builder, method, explicitInterface: false);
            return;
        }

        if (SymbolEqualityComparer.Default.Equals(existing.ReturnType, method.ReturnType))
        {
            return;
        }

        InstrumentedMethodWriter.Write(builder, method, explicitInterface: true);
    }
}
