using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RedisDiagnostic.SourceGenerator;

internal static class InstrumentedDatabaseSourceWriter
{
    internal static string Write(INamedTypeSymbol databaseType)
    {
        var builder = new StringBuilder(64 * 1024);
        AppendClassHeader(builder);

        var emitted = new Dictionary<string, IMethodSymbol>(StringComparer.Ordinal);
        var emittedProperties = new HashSet<string>(StringComparer.Ordinal);
        foreach (var member in DatabaseInterfaceMembers.Enumerate(databaseType))
        {
            if (member is IPropertySymbol property)
            {
                if (!emittedProperties.Add(property.Name))
                {
                    continue;
                }

                InstrumentedPropertyWriter.Write(builder, property);
                continue;
            }

            if (member is IMethodSymbol method && method.MethodKind == MethodKind.Ordinary)
            {
                AppendUniqueMethod(builder, method, emitted);
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendClassHeader(StringBuilder builder)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591");
        builder.AppendLine("#pragma warning disable SER007, SER008");
        builder.AppendLine();
        builder.AppendLine("namespace RedisDiagnostic;");
        builder.AppendLine();
        builder.AppendLine("public sealed class InstrumentedDatabase : global::StackExchange.Redis.IDatabase");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::StackExchange.Redis.IDatabase _inner;");
        builder.AppendLine("    private readonly global::RedisDiagnostic.IRedisMethodMetrics _metrics;");
        builder.AppendLine();
        builder.AppendLine("    public InstrumentedDatabase(global::StackExchange.Redis.IDatabase inner, global::RedisDiagnostic.IRedisMethodMetrics metrics)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(inner);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(metrics);");
        builder.AppendLine("        _inner = inner;");
        builder.AppendLine("        _metrics = metrics;");
        builder.AppendLine("    }");
    }

    private static void AppendUniqueMethod(
        StringBuilder builder,
        IMethodSymbol method,
        Dictionary<string, IMethodSymbol> emitted)
    {
        var key = DatabaseInterfaceMembers.GetSignatureKey(method);
        if (emitted.TryGetValue(key, out var existing))
        {
            if (!SymbolEqualityComparer.Default.Equals(existing.ReturnType, method.ReturnType))
            {
                InstrumentedMethodWriter.Write(builder, method, explicitInterface: true);
            }

            return;
        }

        emitted[key] = method;
        InstrumentedMethodWriter.Write(builder, method, explicitInterface: false);
    }
}
