using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace RedisDiagnostic.SourceGenerator;

internal static class InstrumentedDatabaseSourceWriter
{
    private static readonly HashSet<string> s_passThroughMethods = new HashSet<string>(StringComparer.Ordinal)
    {
        "CreateBatch",
        "CreateTransaction",
    };

    internal static string Write(INamedTypeSymbol databaseType)
    {
        var builder = new StringBuilder(64 * 1024);
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS1591");
        builder.AppendLine();
        builder.AppendLine("namespace RedisDiagnostic;");
        builder.AppendLine();
        builder.AppendLine("public sealed class InstrumentedDatabase : global::StackExchange.Redis.IDatabase");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::StackExchange.Redis.IDatabase _inner;");
        builder.AppendLine("    private readonly global::RedisDiagnostic.IRedisMethodMetrics _metrics;");
        builder.AppendLine();
        builder.AppendLine("    public InstrumentedDatabase(global::StackExchange.Redis.IDatabase inner, global::RedisDiagnostic.IRedisMethodMetrics metrics)");
        builder.AppendLine("    {");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(inner);");
        builder.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(metrics);");
        builder.AppendLine("        _inner = inner;");
        builder.AppendLine("        _metrics = metrics;");
        builder.AppendLine("    }");

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        foreach (var member in EnumerateInstanceMembers(databaseType))
        {
            if (member is IPropertySymbol property)
            {
                var key = "P:" + property.Name;
                if (!emitted.Add(key))
                {
                    continue;
                }

                AppendProperty(builder, property);
                continue;
            }

            if (member is IMethodSymbol method && method.MethodKind == MethodKind.Ordinary)
            {
                var key = "M:" + method.ToDisplayString();
                if (!emitted.Add(key))
                {
                    continue;
                }

                AppendMethod(builder, method);
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IEnumerable<ISymbol> EnumerateInstanceMembers(INamedTypeSymbol databaseType)
    {
        foreach (var member in databaseType.GetMembers())
        {
            if (!member.IsStatic)
            {
                yield return member;
            }
        }

        foreach (var iface in databaseType.AllInterfaces)
        {
            foreach (var member in iface.GetMembers())
            {
                if (!member.IsStatic)
                {
                    yield return member;
                }
            }
        }
    }

    private static void AppendProperty(StringBuilder builder, IPropertySymbol property)
    {
        builder.AppendLine();
        builder.Append("    public ").Append(FormatType(property.Type)).Append(' ').Append(property.Name);
        builder.AppendLine();
        builder.AppendLine("    {");
        if (property.GetMethod is not null)
        {
            builder.Append("        get => _inner.").Append(property.Name).AppendLine(";");
        }

        if (property.SetMethod is not null)
        {
            builder.Append("        set => _inner.").Append(property.Name).AppendLine(" = value;");
        }

        builder.AppendLine("    }");
    }

    private static void AppendMethod(StringBuilder builder, IMethodSymbol method)
    {
        builder.AppendLine();
        builder.Append("    public ");
        builder.Append(FormatType(method.ReturnType));
        builder.Append(' ');
        builder.Append(method.Name);
        if (method.TypeParameters.Length > 0)
        {
            builder.Append('<');
            for (var i = 0; i < method.TypeParameters.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(method.TypeParameters[i].Name);
            }

            builder.Append('>');
        }

        builder.Append('(');
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            AppendParameter(builder, method.Parameters[i]);
        }

        builder.Append(')');
        AppendConstraints(builder, method);
        builder.AppendLine();
        builder.Append("        => ");

        var invocation = BuildInvocation(method);
        if (s_passThroughMethods.Contains(method.Name))
        {
            builder.Append(invocation).AppendLine(";");
            return;
        }

        if (IsAsyncTask(method.ReturnType, out var hasResult))
        {
            builder.Append("_metrics.MeasureAsync(nameof(").Append(method.Name).Append("), () => ").Append(invocation).AppendLine(");");
            return;
        }

        if (method.ReturnsVoid)
        {
            builder.Append("_metrics.Measure(nameof(").Append(method.Name).Append("), () => ").Append(invocation).AppendLine(");");
            return;
        }

        builder.Append("_metrics.Measure(nameof(").Append(method.Name).Append("), () => ").Append(invocation).AppendLine(");");
        _ = hasResult;
    }

    private static void AppendParameter(StringBuilder builder, IParameterSymbol parameter)
    {
        if (parameter.RefKind == RefKind.Ref)
        {
            builder.Append("ref ");
        }
        else if (parameter.RefKind == RefKind.Out)
        {
            builder.Append("out ");
        }
        else if (parameter.RefKind == RefKind.In)
        {
            builder.Append("in ");
        }

        if (parameter.IsParams)
        {
            builder.Append("params ");
        }

        builder.Append(FormatType(parameter.Type)).Append(' ').Append(EscapeIdentifier(parameter.Name));
        if (parameter.HasExplicitDefaultValue)
        {
            builder.Append(" = ").Append(FormatDefaultValue(parameter));
        }
    }

    private static void AppendConstraints(StringBuilder builder, IMethodSymbol method)
    {
        foreach (var typeParameter in method.TypeParameters)
        {
            var constraints = new List<string>();
            if (typeParameter.HasReferenceTypeConstraint)
            {
                constraints.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                    ? "class?"
                    : "class");
            }

            if (typeParameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }

            if (typeParameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            if (typeParameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }

            foreach (var constraintType in typeParameter.ConstraintTypes)
            {
                constraints.Add(FormatType(constraintType));
            }

            if (typeParameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count == 0)
            {
                continue;
            }

            builder.Append(" where ").Append(typeParameter.Name).Append(" : ").Append(string.Join(", ", constraints));
        }
    }

    private static string BuildInvocation(IMethodSymbol method)
    {
        var builder = new StringBuilder();
        builder.Append("_inner.").Append(method.Name);
        if (method.TypeParameters.Length > 0)
        {
            builder.Append('<');
            for (var i = 0; i < method.TypeParameters.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(method.TypeParameters[i].Name);
            }

            builder.Append('>');
        }

        builder.Append('(');
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            var parameter = method.Parameters[i];
            if (parameter.RefKind == RefKind.Ref)
            {
                builder.Append("ref ");
            }
            else if (parameter.RefKind == RefKind.Out)
            {
                builder.Append("out ");
            }
            else if (parameter.RefKind == RefKind.In)
            {
                builder.Append("in ");
            }

            builder.Append(EscapeIdentifier(parameter.Name));
        }

        builder.Append(')');
        return builder.ToString();
    }

    private static bool IsAsyncTask(ITypeSymbol returnType, out bool hasResult)
    {
        hasResult = false;
        if (returnType is not INamedTypeSymbol named)
        {
            return false;
        }

        var fullName = named.OriginalDefinition.ToDisplayString();
        if (fullName == "System.Threading.Tasks.Task")
        {
            return true;
        }

        if (fullName == "System.Threading.Tasks.Task<TResult>")
        {
            hasResult = true;
            return true;
        }

        return false;
    }

    private static string FormatType(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
                | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers));
    }

    private static string FormatDefaultValue(IParameterSymbol parameter)
    {
        var value = parameter.ExplicitDefaultValue;
        var type = parameter.Type;

        if (value is null)
        {
            if (IsNonNullableValueType(type))
            {
                return "default";
            }

            return "null";
        }

        var enumType = GetEnumType(type);
        if (enumType is not null)
        {
            return FormatEnumDefault(enumType, value);
        }

        return value switch
        {
            bool flag => flag ? "true" : "false",
            string text => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(text, quote: true),
            char character => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(character, quote: true),
            float number => FormatFloat(number),
            double number => FormatDouble(number),
            decimal number => number.ToString(CultureInfo.InvariantCulture) + "M",
            uint number => number.ToString(CultureInfo.InvariantCulture) + "U",
            long number => number.ToString(CultureInfo.InvariantCulture) + "L",
            ulong number => number.ToString(CultureInfo.InvariantCulture) + "UL",
            byte or sbyte or short or ushort or int => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0",
            TimeSpan duration => duration == TimeSpan.Zero
                ? "global::System.TimeSpan.Zero"
                : "new global::System.TimeSpan(" + duration.Ticks.ToString(CultureInfo.InvariantCulture) + "L)",
            _ => Convert.ToString(value, CultureInfo.InvariantCulture) ?? "default",
        };
    }

    private static string FormatFloat(float number)
    {
        if (float.IsNegativeInfinity(number))
        {
            return "float.NegativeInfinity";
        }

        if (float.IsPositiveInfinity(number))
        {
            return "float.PositiveInfinity";
        }

        if (float.IsNaN(number))
        {
            return "float.NaN";
        }

        return number.ToString("R", CultureInfo.InvariantCulture) + "F";
    }

    private static string FormatDouble(double number)
    {
        if (double.IsNegativeInfinity(number))
        {
            return "double.NegativeInfinity";
        }

        if (double.IsPositiveInfinity(number))
        {
            return "double.PositiveInfinity";
        }

        if (double.IsNaN(number))
        {
            return "double.NaN";
        }

        return number.ToString("R", CultureInfo.InvariantCulture) + "D";
    }

    private static string FormatEnumDefault(INamedTypeSymbol enumType, object value)
    {
        foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.HasConstantValue && Equals(field.ConstantValue, value))
            {
                return FormatType(enumType) + "." + field.Name;
            }
        }

        return "(" + FormatType(enumType) + ")" + Convert.ToString(value, CultureInfo.InvariantCulture);
    }

    private static INamedTypeSymbol? GetEnumType(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Enum)
        {
            return (INamedTypeSymbol)type;
        }

        if (type is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && named.TypeArguments[0].TypeKind == TypeKind.Enum)
        {
            return (INamedTypeSymbol)named.TypeArguments[0];
        }

        return null;
    }

    private static bool IsNonNullableValueType(ITypeSymbol type)
    {
        return type.IsValueType
               && type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T;
    }

    private static string EscapeIdentifier(string name)
    {
        if (Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            || Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetContextualKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None)
        {
            return "@" + name;
        }

        return name;
    }
}
